language: r
assert: false
r_packages:
 - Rcpp
 - testthat
 - BH
 - RcppArmadillo
 - FSelector
 - foreach
 - dplyr
 - RWeka
 - entropy
 - doParallel
 - rpart
 - iterators
sudo: required
warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'
